name: Panaprisin_Project_Prod

services:
  db:
    image: postgres:18-alpine
    container_name: panaprisin_postgres
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=panaprisin_db
    ports:
      - "6818:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: ghcr.io/firstnasapong/panaprisin_project-web:latest
    container_name: panaprisin_web
    restart: unless-stopped
    ports:
      - "6018:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://admin:password1234@db:5432/panaprisin_db
    depends_on:
      - db

volumes:
  postgres_data: